theme: minima

title: Ashok Acharya
author: Ashok Acharya
description: >-
  Software Engineer & Researcher. Programming Languages, Software Verification,
  Separation Logic. Based in Tokyo.

url: "https://ashok314.github.io"

minima:
  skin: classic

header_pages:
  - index.md
  - books.md
  - films.md
  - poems.md
  - tech.md
  - cooking.md

social_links:
  - { platform: github, user_url: "https://github.com/Ashok314" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/ashok314/" }

plugins:
  - jekyll-feed
