theme: minima

title: ashok314
author: Ashok Acharya
description: >-
  Software Engineer & Researcher. Programming Languages, Software Verification,
  Separation Logic. Based in Tokyo.

url: "https://ashok314.github.io"

minima:
  skin: classic

header_pages:
  - index.md
  - books.md
  - films.md
  - poems.md
  - tech.md
  - cooking.md

social_links:
  - { platform: github, user_url: "https://github.com/Ashok314" }
  - { platform: linkedin, user_url: "https://www.linkedin.com/in/ashok314/" }

exclude:
  - DEV.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed

collections:
  cooking:
    output: true
    permalink: /cooking/:name/
  tech:
    output: true
    permalink: /tech/:name/
  poems:
    output: false

defaults:
  - scope:
      path: ""
      type: cooking
    values:
      layout: recipe
  - scope:
      path: ""
      type: tech
    values:
      layout: article
